// Generated by dts-bundle-generator v9.5.1

import Long$1 from 'long';

/**
 * Represents the state of a participant in a call.
 *
 * @example
 * ```typescript
 * if (participant.state === ParticipantState.Joined) {
 *   console.log('Participant has joined the call');
 * }
 * ```
 */
export declare enum ParticipantState {
	/** Participant is idle and not actively participating */
	Idle = 0,
	/** Participant's device is ringing (incoming call) */
	Ringing = 1,
	/** Participant has joined the call */
	Joined = 2,
	/** Participant has left the call */
	Left = 3,
	/** Participant declined the call invitation */
	Declined = 4,
	/** Participant was removed from the call by another user */
	Kicked = 5,
	/** Participant did not answer the call */
	NoAnswer = 6
}
/**
 * Represents the WebRTC connection state of a participant.
 * Used to track the peer-to-peer or server connection status.
 *
 * @example
 * ```typescript
 * call.on('participantConnectionStateChanged', ({ participant, state }) => {
 *   if (state === ParticipantConnectionState.Connected) {
 *     console.log('Media connection established');
 *   }
 * });
 * ```
 */
export declare enum ParticipantConnectionState {
	/** No connection attempt has been made */
	Idle = 0,
	/** Connection is being established */
	Connecting = 1,
	/** Connection is active and stable */
	Connected = 2,
	/** Connection was lost and is being re-established */
	Reconnecting = 3,
	/** Connection has been terminated */
	Disconnected = 4
}
/**
 * Represents the overall state of a call.
 *
 * @example
 * ```typescript
 * call.on('callStateChanged', ({ call, state }) => {
 *   switch (state) {
 *     case CallState.Connecting:
 *       showConnectingUI();
 *       break;
 *     case CallState.Connected:
 *       showInCallUI();
 *       break;
 *     case CallState.Closed:
 *       showEndCallUI();
 *       break;
 *   }
 * });
 * ```
 */
export declare enum CallState {
	/** Call has not started */
	Idle = "idle",
	/** Call is being established */
	Connecting = "connecting",
	/** Call is active */
	Connected = "connected",
	/** Call has ended */
	Closed = "closed"
}
/**
 * Defines how media is routed in a call.
 *
 * @example
 * ```typescript
 * // Start a peer-to-peer call (direct connection between participants)
 * const call = client.join({
 *   id: 'call-123',
 *   participantIds: ['user1', 'user2'],
 *   mediaFlow: MediaFlow.P2P
 * });
 *
 * // Or use SFU for group calls with better scalability
 * const groupCall = client.join({
 *   id: 'group-call',
 *   participantIds: ['user1', 'user2', 'user3'],
 *   mediaFlow: MediaFlow.SFU
 * });
 * ```
 */
export declare enum MediaFlow {
	/** Peer-to-peer: Direct connection between participants. Best for 1:1 calls. */
	P2P = 0,
	/** Selective Forwarding Unit: Media routed through server. Best for group calls. */
	SFU = 1,
	/** Server-to-WebRTC: Server-side media processing */
	S2W = 2
}
/**
 * Sort order for call detail records (CDR) queries.
 *
 * @example
 * ```typescript
 * const query = client.RecentCallQueryBuilder
 *   .setOrder(CDRRequestOrder.DESC) // Most recent first
 *   .limit(20)
 *   .build();
 * ```
 */
export declare enum CDRRequestOrder {
	/** Sort in ascending order (oldest first) */
	ASC = 0,
	/** Sort in descending order (newest first) */
	DESC = 1
}
/**
 * Types of CDR (Call Detail Record) requests.
 */
export declare enum CDRRequestEvent {
	/** Retrieve recent call history */
	GET_RECENT_CALLS = 0,
	/** Retrieve calls by specific session IDs */
	GET_CALLS_BY_SESSION_IDS = 1,
	/** Delete call records */
	DELETE_RECENT_CALLS = 2
}
/**
 * Pagination direction for CDR queries.
 */
export declare enum CDRRequestDirection {
	/** Load next page of results */
	NEXT = 0,
	/** Load previous page of results */
	PREVIOUS = 1
}
declare class SceytCallException extends Error {
	code?: number | undefined;
	name: string;
	protected _isResendable: boolean;
	get isResendable(): boolean;
	constructor(message?: string, code?: number | undefined, name?: string);
	static BadSignal(code?: number, message?: string): SceytCallException;
	static CallNotFound(code?: number, message?: string): SceytCallException;
	static ParticipantNotFound(code?: number, message?: string): SceytCallException;
	static NotAllowed(code?: number, message?: string): SceytCallException;
	static ParticipantAlreadyExists(code?: number, message?: string): SceytCallException;
	static InternalError(code?: number, message?: string): SceytCallException;
	static NetworkError(code?: number, message?: string): SceytCallException;
	static Timeout(code?: number, message?: string): SceytCallException;
	static BadRequest(code?: number, message?: string): SceytCallException;
	static Unknown(code?: number, message?: string): SceytCallException;
}
/**
 * Event types that can be emitted by a participant.
 * These events indicate changes in the participant's media state.
 */
export type ParticipantEvent = "Mute" | "Unmute" | "Hold" | "Unhold" | "VideoEnabled" | "VideoDisabled" | "ScreenSharingStarted" | "ScreenSharingStopped";
/**
 * Audio publish settings applied when joining a call.
 */
export interface AudioSettings {
	/** Whether to publish audio when joining. Defaults to `true`. Set to `false` to join muted. */
	publishAudio?: boolean;
	/**
	 * Device ID of the preferred audio input device to use when joining.
	 * Obtain device IDs via `navigator.mediaDevices.enumerateDevices()`.
	 */
	preferredAudioRoute?: string | null;
}
/**
 * Video publish settings applied when joining a call.
 */
export interface VideoSettings {
	/** Whether to publish video when joining. Defaults to `true`. Set to `false` to join with camera off. */
	publishVideo?: boolean;
}
/**
 * Broadcast configuration for a call.
 */
export interface BroadcastSettings {
	/** Whether broadcast mode is enabled */
	enabled: boolean;
}
/**
 * Scheduling and broadcast settings for a call.
 */
export interface CallSettings {
	/** Scheduled start time (epoch ms) */
	startsAt?: number;
	/** Expiration timestamp (epoch ms). Must be greater than startsAt if both provided. */
	expiresAt?: number;
	/** Broadcast configuration */
	broadcastSettings?: BroadcastSettings;
	/** Whether the call is persistent (survives all participants leaving) */
	persistent?: boolean;
	/** Whether to notify participants when someone joins */
	notifyOnParticipantJoin?: boolean;
	/** Maximum number of participants allowed in the call */
	maxParticipantsCount?: number;
	/** Type identifier for the call (e.g. 'audio', 'video', custom string) */
	callType?: string;
}
/**
 * Options for creating a call.
 * Pass to `call.create(options)` after preparing a call via `callClient.prepareCall(callId, mediaFlow)`.
 *
 * @example
 * ```typescript
 * const result = callClient.prepareCall('my-call-id', MediaFlow.SFU);
 * result.data?.create({
 *   participantIds: ['user1', 'user2'],
 *   metadata: { topic: 'Team standup' }
 * });
 * ```
 */
export interface CreateCallOptions {
	/** Media routing mode (required) */
	mediaFlow: MediaFlow;
	/** Optional metadata to attach to the call */
	metadata?: CallMetadata;
	/** Array of user IDs to invite to the call */
	participantIds?: string[];
	/** Whether this is a video call */
	videoCall?: boolean;
	/** Scheduling and broadcast settings */
	settings?: CallSettings;
}
/**
 * Options for joining a call.
 * Pass to `call.join(options)` after preparing a call via `callClient.prepareCall(callId, mediaFlow)`.
 *
 * @example
 * ```typescript
 * const result = callClient.prepareCall('call-123', MediaFlow.P2P);
 * result.data?.join({
 *   audioSettings: { publishAudio: true },
 *   videoSettings: { publishVideo: false }
 * });
 * ```
 */
export interface JoinCallOptions {
	/** Audio publish settings for the call */
	audioSettings?: AudioSettings;
	/** Video publish settings for the call */
	videoSettings?: VideoSettings;
	/** Whether to use a media proxy server */
	useMediaProxy?: boolean;
	/** Optional array of audio tracks to use. If not provided, microphone will be requested. */
	localAudioTracks?: MediaStreamTrack[];
	/** Optional array of video tracks to use. If not provided, camera will be requested. */
	localVideoTracks?: MediaStreamTrack[];
}
/**
 * Raw participant data as received from the server.
 * Use the `Participant` class for a richer API.
 */
export interface IParticipant {
	/** User ID of the participant */
	id: string;
	/** Client ID for multi-device support */
	clientId: string;
	/** Whether this participant is the presenter */
	presenter?: boolean;
	/** Whether the participant's camera is on */
	videoEnabled?: boolean;
	/** Whether the participant's microphone is muted */
	muted?: boolean;
	/** Whether the participant is on hold */
	onHold?: boolean;
	/** Whether the participant is sharing their screen */
	screenSharing?: boolean;
	/** Current participation state */
	state?: ParticipantState;
	/** Current media connection state */
	connectionState?: ParticipantConnectionState;
	/** Whether the call was silenced for this participant */
	isCallSilenced?: boolean;
}
type CallMetadata = {
	[key: string]: string | number;
};
/**
 * Raw call data as received from the server.
 * Use the `Call` class for a richer API with methods and events.
 */
export interface ICall {
	/** Unique call identifier */
	readonly id: string;
	/** Server-assigned session identifier */
	readonly sessionId: string;
	/** Media routing mode */
	readonly mediaFlow: MediaFlow;
	/** User ID of the call creator */
	readonly createdBy: string;
	/** Call metadata */
	metadata: CallMetadata;
	/** List of participants */
	participants: IParticipant[];
	/** Timestamp when the call started (milliseconds since epoch) */
	createdAt?: number;
	settings?: CallSettings;
}
/**
 * Participant information in a Call Detail Record (CDR).
 * Represents historical data about a participant's involvement in a past call.
 */
export interface ICDRParticipant {
	/** User ID of the participant */
	userId: string;
	/** Client ID of the participant */
	clientId: string;
	/** Whether this participant initiated the call */
	originator: boolean;
	/** Timestamp when the participant joined (milliseconds since epoch) */
	joinedAt: Long$1;
	/** Timestamp when the participant left (milliseconds since epoch) */
	leftAt: Long$1;
	/** Timestamp when media connection was established */
	mediaConnectedAt: Long$1;
	/** Final state of the participant (joined, declined, no_answer, etc.) */
	state: string;
	/** Whether the call was silenced for this participant */
	isCallSilenced?: boolean;
}
/**
 * Call Detail Record (CDR) representing a historical call.
 * Use `RecentCallQueryBuilder` to retrieve CDRs.
 *
 * @example
 * ```typescript
 * const query = new client.RecentCallQueryBuilder()
 *   .setOrder(CDRRequestOrder.DESC)
 *   .limit(20)
 *   .build();
 *
 * const { records } = await query.loadNextPage();
 * records.forEach((cdr: ICallDetailRecord) => {
 *   const duration = cdr.endedAt - cdr.startedAt;
 *   console.log(`Call ${cdr.callId} lasted ${duration}ms`);
 * });
 * ```
 */
export interface ICallDetailRecord {
	/** Server-assigned session identifier (int64 from proto) */
	sessionId: Long$1;
	/** Unique call identifier */
	callId: string;
	/** User ID of the call initiator */
	originatorId: string;
	/** Media flow type (0=P2P, 1=SFU, 2=S2W) */
	readonly mediaFlow: number;
	/** Call metadata */
	metadata: CallMetadata;
	/** Call start timestamp (milliseconds since epoch) */
	createdAt: number;
	/** Call end timestamp (milliseconds since epoch) */
	endedAt: number;
	/** Final call state */
	state: string;
	/** List of participants with their individual CDR data */
	participants: ICDRParticipant[];
}
interface ICDRResponse {
	/** Type of CDR request */
	event: CDRRequestEvent;
	/** Request identifier */
	id: string;
	/** Response containing call records */
	getRecentCallsResponse: IGetRecentCallsResponse;
	/** List of session IDs (for session ID-based queries) */
	sessionIdList: {
		items: Long$1[];
	};
}
interface IGetRecentCallsResponse {
	/** Token for fetching the next page of results */
	nextToken: string;
	/** Array of call detail records */
	records: ICallDetailRecord[];
}
/**
 * Generic result wrapper for call client operations.
 * Contains either a success response with data or an error.
 */
export interface CallClientResult<T> {
	success?: boolean;
	data?: T;
	error?: SceytCallException;
}
/**
 * Represents a participant in a call.
 * Contains information about the participant's identity, media state, and connection status.
 *
 * @example
 * ```typescript
 * // Access participant information
 * call.on('participantStateChanged', ({ participant, state }) => {
 *   console.log(`Participant ${participant.id} state: ${state}`);
 *   console.log(`Muted: ${participant.muted}`);
 *   console.log(`Video enabled: ${participant.videoEnabled}`);
 * });
 *
 * // Access participant's audio/video tracks
 * participant.audioTracks.forEach(track => {
 *   const audioElement = document.createElement('audio');
 *   audioElement.srcObject = new MediaStream([track]);
 *   audioElement.play();
 * });
 * ```
 */
export declare class Participant {
	/** Unique identifier for the participant (user ID) */
	id: string;
	/** Client identifier for multi-device support. Empty string if not applicable. */
	clientId: string;
	/** Whether the participant's microphone is muted */
	muted: boolean;
	/** Whether the participant is on hold */
	onHold: boolean;
	/** Whether the participant's camera is enabled */
	videoEnabled: boolean;
	/** Whether the participant is sharing their screen */
	screenSharing: boolean;
	/** Array of audio tracks from this participant. Use these to play participant's audio. */
	audioTracks: MediaStreamTrack[];
	/** Array of video tracks from this participant. Use these to display participant's video. */
	videoTracks: MediaStreamTrack[];
	/** Current state of the participant in the call (Idle, Ringing, Joined, Left, etc.) */
	state: ParticipantState;
	/** Current WebRTC connection state of the participant */
	connectionState: ParticipantConnectionState;
}
interface ActiveSpeakerInfo {
	participant: Participant;
	audioLevel: number;
	smoothedAudioLevel: number;
	isSpeaking: boolean;
	speakingStartTime: number;
}
type EventHandler<T> = (data: T) => void;
export type Unsubscribe = () => void;
declare class TypedEventEmitter<EventMap extends Record<string, any>> {
	listeners: Map<keyof EventMap, Set<EventHandler<any>>>;
	/**
	 * Subscribe to an event.
	 * @param event - The event name to subscribe to
	 * @param handler - The callback function to invoke when the event is emitted
	 * @returns An unsubscribe function to remove the listener
	 */
	on<K extends keyof EventMap>(event: K, handler: EventHandler<EventMap[K]>): Unsubscribe;
	/**
	 * Emit an event to all registered listeners.
	 * @param event - The event name to emit
	 * @param data - The data to pass to all listeners
	 */
	protected emit<K extends keyof EventMap>(event: K, data: EventMap[K]): void;
	/**
	 * Remove a specific listener or all listeners for an event.
	 * @param event - The event name
	 * @param handler - Optional specific handler to remove. If omitted, removes all listeners for the event.
	 */
	off<K extends keyof EventMap>(event: K, handler?: EventHandler<EventMap[K]>): void;
	/**
	 * Remove all event listeners.
	 */
	removeAllListeners(): void;
	/**
	 * Get the number of listeners for a specific event.
	 * @param event - The event name
	 * @returns The number of listeners
	 */
	listenerCount<K extends keyof EventMap>(event: K): number;
}
/**
 * Event map for Call class.
 * Use with `call.on(eventName, handler)` to subscribe to events.
 *
 * @example
 * ```typescript
 * const unsubscribe = call.on('callStateChanged', ({ call, state }) => {
 *   console.log(`Call ${call.id} state changed to ${state}`);
 * });
 *
 * // Later, to unsubscribe:
 * unsubscribe();
 * ```
 */
export interface CallEventMap {
	/** Fired when an audio track is added for a participant */
	audioTrackAdded: {
		call: Call;
		participant: Participant;
		track: MediaStreamTrack;
	};
	/** Fired when an audio track is removed for a participant */
	audioTrackRemoved: {
		call: Call;
		participant: Participant;
	};
	/** Fired when a video track is added for a participant */
	videoTrackAdded: {
		call: Call;
		participant: Participant;
		track: MediaStreamTrack;
	};
	/** Fired when a video track is removed for a participant */
	videoTrackRemoved: {
		call: Call;
		participant: Participant;
	};
	/** Fired when the call state changes (Idle, Connecting, Connected, Closed) */
	callStateChanged: {
		call: Call;
		state: CallState;
	};
	/** Fired when a participant's state changes (Idle, Ringing, Joined, Left, etc.) */
	participantStateChanged: {
		call: Call;
		participant: Participant;
		state: ParticipantState;
		reason?: string | number | undefined;
	};
	/** Fired when a participant's connection state changes */
	participantConnectionStateChanged: {
		call: Call;
		participant: Participant;
		state: ParticipantConnectionState;
	};
	/** Fired when a participant triggers an event (Mute, Unmute, Hold, etc.) */
	participantEvent: {
		call: Call;
		participant: Participant;
		event: ParticipantEvent;
	};
	/** Fired when participants are added to the call */
	participantsAdded: {
		call: Call;
		participants: Participant[];
	};
	/** Fired when participants are removed from the call */
	participantsRemoved: {
		call: Call;
		participants: Participant[];
	};
	/** Fired when the active speakers list changes */
	activeSpeakersChanged: {
		call: Call;
		activeSpeakers: ActiveSpeakerInfo[];
	};
	/** Fired when the dominant speaker changes */
	dominantSpeakerChanged: {
		call: Call;
		dominantSpeaker: ActiveSpeakerInfo | null;
	};
	/** Fired when the media flow changes (P2P, SFU, S2W) */
	mediaFlowChanged: {
		call: Call;
		mediaFlow: MediaFlow;
	};
	/** Fired when the call session is renewed (new sessionId assigned by server) */
	sessionRenewed: {
		call: Call;
		sessionId: string;
	};
}
/**
 * Event map for SceytCallClient class.
 * Use with `client.on(eventName, handler)` to subscribe to events.
 *
 * @example
 * ```typescript
 * const unsubscribe = client.on('invitedToCall', ({ call }) => {
 *   console.log(`Incoming call: ${call.id}`);
 * });
 * ```
 */
export interface CallClientEventMap {
	/** Fired when the user is invited to a call */
	invitedToCall: {
		call: Call;
	};
	/** Fired when the list of ongoing calls changes */
	ongoingCallsUpdated: {
		calls: Call[];
	};
}
/**
 * Represents an active call session.
 * Provides methods to control the call, manage participants, and handle media.
 *
 * @example
 * ```typescript
 * // Subscribe to call events
 * const unsubscribe = call.on('callStateChanged', ({ call, state }) => {
 *   console.log(`Call state: ${state}`);
 * });
 *
 * // Control audio/video
 * call.mute(true);  // Mute microphone
 * await call.enableVideo(true);  // Enable camera
 *
 * // Add participants to the call
 * await call.addParticipants(['user3', 'user4']);
 *
 * // Unsubscribe when done
 * unsubscribe();
 * ```
 */
export declare class Call extends TypedEventEmitter<CallEventMap> {
	/** Unique identifier for this call */
	id: string;
	/** Server-assigned session identifier. Empty string until the call is connected. */
	sessionId: string;
	/** Current media routing mode (P2P, SFU, or S2W) */
	mediaFlow: MediaFlow;
	/** List of all participants in the call, including remote participants */
	participants: Participant[];
	/** The local user's participant object */
	localParticipant: Participant;
	/** User ID of the call creator/initiator */
	createdBy: string;
	/** Optional metadata associated with the call */
	metadata?: CallMetadata;
	/** Current state of the call (Idle, Connecting, Connected, Closed) */
	state: CallState;
	/** Whether video is currently enabled for the local participant */
	videoEnabled: boolean;
	/** Whether the call was silenced (no ringtone) when initiated */
	isCallSilenced: boolean;
	/** Whether this is a video call */
	videoCall: boolean;
	/** Scheduling and broadcast settings for this call */
	settings?: CallSettings;
	/** Current list of active speakers in the call */
	get activeSpeakers(): ActiveSpeakerInfo[];
	set activeSpeakers(speakers: ActiveSpeakerInfo[]);
	/**
	 * Add new participants to the call.
	 * The participants will receive an invitation to join.
	 *
	 * @param ids - Array of user IDs to invite to the call
	 *
	 * @example
	 * ```typescript
	 * // Add multiple users to an ongoing call
	 * await call.addParticipants(['user3', 'user4']);
	 * ```
	 */
	addParticipants(ids: string[]): CallClientResult<boolean>;
	/**
	 * Join this call with the given options.
	 * The call must have been previously prepared via `callClient.prepareCall()`
	 * or received via the `invitedToCall` event.
	 *
	 * @param options - Join options (audio settings, media proxy, local tracks)
	 * @param createOptions - Optional create options to create-and-join in one step
	 * @param errorCallback - Optional callback invoked if the server rejects the JOIN signal
	 * @returns A `CallClientResult` containing this Call object on success
	 *
	 * @example
	 * ```typescript
	 * const result = callClient.prepareCall('call-123', MediaFlow.P2P);
	 * if (result.success && result.data) {
	 *   result.data.join(
	 *     { audioSettings: { publishAudio: true }, videoSettings: { publishVideo: false } },
	 *     { participantIds: ['user2'] }
	 *   );
	 * }
	 * ```
	 */
	join(options: JoinCallOptions, errorCallback?: (result: CallClientResult<Call>) => void): CallClientResult<Call>;
	/**
	 * Reject this incoming call.
	 * Use this when the user declines to answer a call.
	 *
	 * @param reason - Optional reason for rejection (e.g., 'busy', 'declined')
	 * @param errorCallback - Optional callback invoked if the server rejects the DECLINE signal
	 *
	 * @example
	 * ```typescript
	 * callClient.on('invitedToCall', ({ call }) => {
	 *   call.reject('busy');
	 * });
	 * ```
	 */
	reject(reason?: string, errorCallback?: (result: CallClientResult<boolean>) => void): CallClientResult<boolean>;
	/**
	 * Leave this active call.
	 * This ends your participation in the call. Other participants will continue.
	 *
	 * @example
	 * ```typescript
	 * call.leave();
	 * ```
	 */
	leave(): CallClientResult<boolean>;
	/**
	 * Create a call link without joining.
	 * Participants in `participantIds` will receive an INVITE from the server.
	 * The creator does not join automatically — call `call.join(options)` to participate.
	 *
	 * @param options - Call creation options (participantIds, metadata, videoCall, settings)
	 * @param errorCallback - Optional callback invoked if the server rejects the CREATE signal
	 * @returns A `CallClientResult` indicating success or failure
	 *
	 * @example
	 * ```typescript
	 * const result = callClient.prepareCall('my-call-link', MediaFlow.SFU);
	 * if (result.success && result.data) {
	 *   result.data.create({
	 *     participantIds: ['user1', 'user2'],
	 *     metadata: { topic: 'Team standup' }
	 *   });
	 * }
	 * ```
	 */
	create(errorCallback?: (result: CallClientResult<Call>) => void): CallClientResult<Call>;
	kickParticipants(ids: string[]): CallClientResult<boolean>;
	/**
	 * Switch the call from P2P (peer-to-peer) to SFU (Selective Forwarding Unit) mode.
	 * Use this when adding more participants to a P2P call or when you need server-side media routing.
	 *
	 * @example
	 * ```typescript
	 * // Switch to SFU mode for better scalability
	 * await call.switchToSFU();
	 * ```
	 */
	switchToSFU(errorCallback?: (result: CallClientResult<boolean>) => void): Promise<CallClientResult<boolean>>;
	/**
	 * Mute or unmute the local participant's microphone.
	 * Other participants will be notified of the mute state change.
	 *
	 * @param mute - `true` to mute, `false` to unmute
	 *
	 * @example
	 * ```typescript
	 * // Mute microphone
	 * call.mute(true);
	 *
	 * // Unmute microphone
	 * call.mute(false);
	 * ```
	 */
	mute(mute: boolean, errorCallback?: (result: CallClientResult<boolean>) => void): CallClientResult<boolean>;
	/**
	 * Put the call on hold or resume it.
	 * When on hold, audio/video is paused but the call remains active.
	 *
	 * @param hold - `true` to put on hold, `false` to resume
	 *
	 * @example
	 * ```typescript
	 * // Put call on hold
	 * call.hold(true);
	 *
	 * // Resume call
	 * call.hold(false);
	 * ```
	 */
	hold(hold: boolean): CallClientResult<boolean>;
	/**
	 * Get the local audio tracks being sent in this call.
	 * @returns Array of MediaStreamTrack objects for audio
	 */
	get localAudioTracks(): MediaStreamTrack[];
	/**
	 * Get the local video tracks being sent in this call.
	 * @returns Array of MediaStreamTrack objects for video
	 */
	get localVideoTracks(): MediaStreamTrack[];
	/**
	 * Set the muted state. Use `mute()` method instead to also notify other participants.
	 */
	set muted(muted: boolean);
	/**
	 * Whether the local participant's microphone is muted.
	 */
	get muted(): boolean;
	/**
	 * Set the muted state. Use `startScreenShare() or stopScreenShare` method instead to also notify other participants.
	 */
	set screenSharing(muted: boolean);
	/**
	 * Whether the local participant's microphone is muted.
	 */
	get screenSharing(): boolean;
	/**
	 * Set the hold state. Use `hold()` method instead to also notify other participants.
	 */
	set onHold(onHold: boolean);
	/**
	 * Whether the call is currently on hold.
	 */
	get onHold(): boolean;
	/**
	 * Enable or disable video for the local participant.
	 * This will request camera access if enabling video.
	 *
	 * @param videoEnabled - `true` to enable video, `false` to disable
	 *
	 * @example
	 * ```typescript
	 * // Enable camera
	 * await call.enableVideo(true);
	 *
	 * // Disable camera
	 * await call.enableVideo(false);
	 * ```
	 */
	enableVideo(videoEnabled: boolean, errorCallback?: (result: CallClientResult<boolean>) => void): Promise<CallClientResult<boolean>>;
	/**
	 * Start sharing your screen with other participants.
	 * This will prompt the user to select a screen, window, or tab to share.
	 *
	 * @example
	 * ```typescript
	 * await call.startScreenShare();
	 * ```
	 */
	startScreenShare(errorCallback?: (result: CallClientResult<boolean>) => void): Promise<CallClientResult<boolean>>;
	/**
	 * Stop sharing your screen.
	 *
	 * @example
	 * ```typescript
	 * await call.stopScreenShare();
	 * ```
	 */
	stopScreenShare(errorCallback?: (result: CallClientResult<boolean>) => void): Promise<CallClientResult<boolean>>;
	/**
	 * Get a list of available video input devices (cameras).
	 *
	 * @returns Promise resolving to an array of MediaDeviceInfo objects
	 *
	 * @example
	 * ```typescript
	 * const cameras = await call.getAvailableVideoDevices();
	 * cameras.forEach(camera => {
	 *   console.log(`${camera.label}: ${camera.deviceId}`);
	 * });
	 * ```
	 */
	getAvailableVideoDevices(): Promise<CallClientResult<MediaDeviceInfo[]>>;
	/**
	 * Get a list of available audio input devices (microphones).
	 *
	 * @returns Promise resolving to an array of MediaDeviceInfo objects
	 *
	 * @example
	 * ```typescript
	 * const microphones = await call.getAvailableAudioDevices();
	 * microphones.forEach(mic => {
	 *   console.log(`${mic.label}: ${mic.deviceId}`);
	 * });
	 * ```
	 */
	getAvailableAudioDevices(): Promise<CallClientResult<MediaDeviceInfo[]>>;
	/**
	 * Switch to a different video input device (camera).
	 *
	 * @param deviceId - The device ID of the camera to use
	 *
	 * @example
	 * ```typescript
	 * const cameras = await call.getAvailableVideoDevices();
	 * if (cameras.length > 1) {
	 *   await call.selectVideoDevice(cameras[1].deviceId);
	 * }
	 * ```
	 */
	selectVideoDevice(deviceId: string): Promise<CallClientResult<boolean>>;
	/**
	 * Switch to a different audio input device (microphone).
	 *
	 * @param deviceId - The device ID of the microphone to use
	 *
	 * @example
	 * ```typescript
	 * const microphones = await call.getAvailableAudioDevices();
	 * if (microphones.length > 1) {
	 *   await call.selectAudioDevice(microphones[1].deviceId);
	 * }
	 * ```
	 */
	selectAudioDevice(deviceId: string): Promise<CallClientResult<boolean>>;
	/**
	 * Get WebRTC statistics for all participants in the call.
	 * Useful for monitoring call quality and debugging connection issues.
	 *
	 * @returns Promise resolving to an array of stats objects for each participant
	 *
	 * @example
	 * ```typescript
	 * const stats = await call.getStats();
	 * console.log('Call statistics:', stats);
	 * ```
	 */
	getStats: () => Promise<CallClientResult<RTCStatsReport[]>>;
	/**
	 * Get WebRTC statistics for a specific participant.
	 *
	 * @param participant - The participant to get stats for
	 * @returns Promise resolving to the RTCStatsReport or null if not available
	 *
	 * @example
	 * ```typescript
	 * const participant = call.participants[0];
	 * const stats = await call.getParticipantStats(participant);
	 * ```
	 */
	getParticipantStats: (participant: Participant) => Promise<CallClientResult<RTCStatsReport | null>>;
	/**
	 * Find a participant by their user ID and client ID.
	 *
	 * @param id - The user ID of the participant
	 * @param clientId - The client ID of the participant (for multi-device support)
	 * @returns The Participant object if found, undefined otherwise
	 *
	 * @example
	 * ```typescript
	 * const participant = call.getParticipant('user123', 'device1');
	 * if (participant) {
	 *   console.log(`Found participant: ${participant.id}`);
	 * }
	 * ```
	 */
	getParticipant(id: string, clientId: string): Participant | undefined;
	/**
	 * Send a ringing signal to indicate that the call is being answered.
	 * Use this when receiving an incoming call to notify the caller that you're about to answer.
	 *
	 * @example
	 * ```typescript
	 * // When receiving an incoming call
	 * client.on('invitedToCall', ({ call }) => {
	 *   call.sendRinging();  // Notify caller that we're ringing
	 *   // Show incoming call UI...
	 * });
	 * ```
	 */
	sendRinging(errorCallback?: (error: CallClientResult<boolean>) => void): CallClientResult<boolean>;
}
declare const colors: {
	green: string;
	blue: string;
	"light-green": string;
	"light-blue": string;
	yellow: string;
	magenta: string;
	cyan: string;
	reset: string;
	orange: string;
	red: string;
	white: string;
};
export type ColorOption = keyof typeof colors;
export interface LogEntry {
	level: "warn" | "error" | "info" | "debug" | "trace";
	message: string;
	prefix: string;
	args?: any[];
	color?: string;
	time?: string;
}
type LogListener = (logEntry: LogEntry) => void;
export declare const addLogListener: (listener: LogListener) => void;
export declare const removeLogListener: (listener: LogListener) => void;
export declare const createLogger: (prefix: string, defaultColor?: ColorOption) => {
	trace: (message: string, logOptions?: {
		color?: ColorOption;
		time?: string;
	}) => void;
	debug: (message: string, logOptions?: {
		color?: ColorOption;
		time?: string;
	}) => void;
	info: (message: string, logOptions?: {
		color?: ColorOption;
		time?: string;
	}) => void;
	warn: (message: string, logOptions?: {
		color?: ColorOption;
		time?: string;
	}) => void;
	error: (message: string, logOptions?: {
		color?: ColorOption;
		time?: string;
	}) => void;
};
declare class QueryBuilder {
	count: number;
}
declare class RecentCallQuery {
	loadNextPage: () => Promise<{
		records: ICallDetailRecord[];
		hasNext: boolean;
	}>;
	deleteCalls: () => Promise<ICDRResponse | undefined>;
}
declare class RecentCallQueryBuilder extends QueryBuilder {
	order: CDRRequestOrder;
	count: number;
	sessionId?: number;
	participantCount: number;
	event: CDRRequestEvent;
	direction: CDRRequestDirection;
	chatClient: any;
	sessionIdList?: Long$1[];
	setSessionIdList: (sessionIdList: Long$1[]) => this;
	setEvent: (event: CDRRequestEvent) => this;
	setSessionId: (sessionId: number) => this;
	limit: (count: number) => this;
	setParticipantCount: (count: number) => this;
	setOrder: (order: CDRRequestOrder) => this;
	setDirection: (direction: CDRRequestDirection) => this;
	build: () => RecentCallQuery;
}
/**
 * Main entry point for the Sceyt Call SDK.
 * Use this class to initiate calls, handle incoming calls, and manage call state.
 *
 * @example
 * ```typescript
 * import SceytCallClient, { MediaFlow } from 'sceyt-call';
 *
 * // Initialize the call client with your chat client
 * const callClient = new SceytCallClient(chatClient);
 *
 * // Listen for incoming calls
 * callClient.on('invitedToCall', ({ call }) => {
 *   console.log(`Incoming call from ${call.createdBy}`);
 *   // Show incoming call UI...
 * });
 *
 * // Start a new call
 * const result = callClient.prepareCall('my-call-id');
 *
 * if (result.success && result.data) {
 *   const call = result.data;
 *   // Handle call events
 *   call.on('callStateChanged', ({ state }) => {
 *     console.log(`Call state: ${state}`);
 *   });
 *   // Join when ready
 *   call.join(
 *     { audioSettings: { publishAudio: true }, videoSettings: { publishVideo: true } },
 *     { participantIds: ['user1', 'user2'] }
 *   );
 * }
 * ```
 */
export declare class SceytCallClient extends TypedEventEmitter<CallClientEventMap> {
	/**
	 * Create a new SceytCallClient instance.
	 *
	 * @param chatClient - The Sceyt Chat client instance to use for signaling
	 *
	 * @example
	 * ```typescript
	 * const callClient = new SceytCallClient(chatClient);
	 * ```
	 */
	constructor(chatClient: any);
	/**
	 * Get all currently active calls.
	 * Returns an array of Call objects representing ongoing calls.
	 *
	 * @example
	 * ```typescript
	 * const calls = callClient.activeCalls;
	 * console.log(`Currently in ${calls.length} call(s)`);
	 * ```
	 */
	get activeCalls(): Call[];
	/**
	 * Prepare a new call without joining it.
	 * Creates a Call object and registers it in `activeCalls`,
	 * but does not send any signaling or start media connections.
	 * Call `call.create(options)` or `call.join(options)` when ready.
	 *
	 * @param callId - Unique identifier for the call
	 * @param createOptions - Optional call configuration (participants, settings, metadata)
	 *
	 * @example
	 * ```typescript
	 * const result = callClient.prepareCall('call-123', {
	 *   participantIds: ['user1', 'user2'],
	 *   settings: { startsAt: Date.now() }
	 * });
	 * if (result.success && result.data) {
	 *   result.data.create();
	 * }
	 * ```
	 */
	prepareCall(callId: string, createOptions?: CreateCallOptions): CallClientResult<Call>;
	/**
	 * Get a call by its ID. Returns the local active call if found,
	 * otherwise fetches it from the server.
	 *
	 * @param callId - The unique identifier of the call
	 * @returns A promise resolving to the Call object
	 *
	 * @example
	 * ```typescript
	 * const result = await callClient.fetchCall('call-123');
	 * if (result.success && result.data) {
	 *   console.log(`Call state: ${result.data.state}`);
	 * }
	 * ```
	 */
	fetchCall: (callId: string) => Promise<CallClientResult<Call>>;
	/**
	 * Refresh and get the list of all ongoing calls.
	 * This fetches the latest call information from the server.
	 *
	 * @returns Array of all active Call objects
	 *
	 * @example
	 * ```typescript
	 * const calls = callClient.getOngoingCalls();
	 * calls.forEach(call => {
	 *   console.log(`Call ${call.id}: ${call.participants.length} participants`);
	 * });
	 * ```
	 */
	getOngoingCalls: () => Call[];
	/**
	 * Subscribe to SDK log events.
	 * Useful for debugging and monitoring SDK behavior.
	 *
	 * @param callback - Function called for each log entry
	 * @returns Unsubscribe function to stop receiving logs
	 *
	 * @example
	 * ```typescript
	 * const unsubscribe = callClient.onLog((entry) => {
	 *   console.log(`[${entry.level}] ${entry.prefix}: ${entry.message}`);
	 * });
	 *
	 * // Later, stop listening
	 * unsubscribe();
	 * ```
	 */
	onLog: (callback: (logEntry: LogEntry) => void) => () => void;
	/**
	 * Access the RecentCallQueryBuilder to query call history (CDR - Call Detail Records).
	 * Use this to retrieve past calls, filter by criteria, and paginate through results.
	 *
	 * @example
	 * ```typescript
	 * // Query recent calls
	 * const query = new callClient.RecentCallQueryBuilder()
	 *   .setOrder(CDRRequestOrder.DESC)
	 *   .limit(20)
	 *   .build();
	 *
	 * const { records, hasNext } = await query.loadNextPage();
	 * records.forEach(record => {
	 *   console.log(`Call: ${record.callId}, Duration: ${record.endedAt - record.startedAt}ms`);
	 * });
	 * ```
	 */
	get RecentCallQueryBuilder(): typeof RecentCallQueryBuilder;
}
/**
 * Wrapper class for an audio MediaStreamTrack.
 * Provides convenient methods to manage audio track state.
 *
 * @example
 * ```typescript
 * // Access audio tracks from a participant
 * participant.audioTracks.forEach(track => {
 *   const audioTrack = new AudioTrack(track);
 *   console.log(`Audio track ID: ${audioTrack.id}`);
 *
 *   // Disable the audio track
 *   audioTrack.enabled = false;
 * });
 * ```
 */
export declare class AudioTrack {
	/** Unique identifier for the audio track */
	readonly id: string;
	/** The underlying MediaStreamTrack object */
	readonly audioTrack: MediaStreamTrack;
	/**
	 * Enable or disable the audio track.
	 * When disabled, the track will not produce any audio output.
	 */
	set enabled(value: boolean);
	/**
	 * Whether the audio track is currently enabled.
	 */
	get enabled(): boolean;
}
/**
 * Wrapper class for a video MediaStreamTrack.
 * Provides convenient methods to manage video track state.
 *
 * @example
 * ```typescript
 * // Access video tracks from a participant
 * participant.videoTracks.forEach(track => {
 *   const videoTrack = new VideoTrack(track);
 *   console.log(`Video track ID: ${videoTrack.id}`);
 *
 *   // Attach to a video element
 *   const videoElement = document.createElement('video');
 *   videoElement.srcObject = new MediaStream([videoTrack.videoTrack]);
 *   videoElement.play();
 * });
 * ```
 */
export declare class VideoTrack {
	/** Unique identifier for the video track */
	readonly id: string;
	/** The underlying MediaStreamTrack object */
	readonly videoTrack: MediaStreamTrack;
	/**
	 * Enable or disable the video track.
	 * When disabled, the track will not produce any video frames.
	 */
	set enabled(value: boolean);
	/**
	 * Whether the video track is currently enabled.
	 */
	get enabled(): boolean;
}

export {
	SceytCallClient as default,
};

export {};
